[tool.poetry]
name = "geollama"
version = "0.1.0"
description = "A Python package for estimating sample thickness in cryo electron tomograms"
authors = ["Neville Yee <neville.yee@rfi.ac.uk>"]
license = "Apache V2"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.12"
numpy = "1.22"
plotly = "^5.17.0"
scikit-image = "^0.21.0"
scikit-learn = "^1.3.1"
mrcfile = "^1.4.3"
scipy = "1.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
