[build-system]
requires = ["poetry-core", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[project]
name = "GeoLlama"
dynamic = ["version"]
description = "A Python package for estimating sample thickness in cryo electron tomograms"
authors = [
    {name = "Neville B.-y. Yee"},
]
license = {text = "Apache License V.2"}
readme = "README.md"
packages = [{include = "geollama"}]

requires-python = ">=3.10"
dependencies = [
	"numpy >= 2.2.6",
	"plotly >= 6.3.0",
	"scikit-image >= 0.25.2",
	"scikit-learn >= 1.7.1",
	"mrcfile >= 1.5.4",
	"scipy >= 1.15.3",
	"pytest >= 8.4.1",
	"typer >= 0.16.0",
	"rich >= 14.1.0",
	"pandas >= 2.3.1",
	"tabulate >= 0.9.0",
	"starfile >= 0.5.13",
	"matplotlib >= 3.10.5",
	"pyinstrument >= 5.1.1",
	"icecream >= 2.1.5",
	"typing-extensions >= 4.14.1",
	"ruamel-yaml >= 0.18.14",
	"umap-learn >= 0.5.9.post2",
	"papermill >= 2.6.0",
	"ipython >= 8.37.0",
	"ipykernel >= 6.30.1",
	"seaborn >= 0.13.2",
	"nbconvert >= 7.16.6",
	"opencv-python >= 4.12.0.88",
	"pip >= 25.0",
]

[tool.poetry]
version = "1.1.0"
[tool.poetry.scripts]
geollama = "geollama.main:app"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.poetry-dynamic-versioning.from-file]
source = "geollama/__init__.py"
pattern = '''^__version__\s*=\s*"([0-9]+\.[0-9]+\.[0-9]+.*?)"'''

