name: Python CI/CD

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.14

      - name: Install package
        run: |
          python3 -m pip install --upgrade pip
          pip3 install poetry
          pip3 install -r requirements.txt
          poetry install --no-interaction --only-root

      - name: Run tests
        run: |
          pip3 install pytest pytest-cov
          pytest --cov=com --cov-report=xml --cov-report=html
